ALTER TABLE ANO ADD CONSTRAINT CK_LIMITE_ANO 
CHECK (ano >= 1970);

ALTER TABLE MES ADD CONSTRAINT CK_LIMITE_MES 
CHECK (mes > 0 and mes <13);


ALTER TABLE FABRICANTE DROP COLUMN Cidade;
ALTER TABLE FABRICANTE DROP COLUMN endereco;
ALTER TABLE FABRICANTE DROP COLUMN uf;
ALTER TABLE FABRICANTE ADD idEndereco INT;

CREATE TABLE ENDERECO (
	idEndereco	INT PRIMARY KEY IDENTITY(1,1),
	logradouro	VARCHAR(50)	NOT NULL,
	numero		INT			NOT NULL,
	cidade		VARCHAR(50) NOT NULL,
	UF			CHAR(2)		NOT NULL,
	bairro		VARCHAR(50)	NOT NULL,
	CEP			CHAR(8)		NOT NULL
)

ALTER TABLE FABRICANTE ADD CONSTRAINT FK_idendereco
FOREIGN KEY (idEndereco) REFERENCES ENDERECO (idEndereco);




ALTER TABLE VENDAS_ANUAIS DROP CONSTRAINT PK_VENDAS;

ALTER TABLE VENDAS_ANUAIS
ALTER COLUMN ID_VEICULO INT NOT NULL;

ALTER TABLE VENDAS_ANUAIS
ALTER COLUMN ID_ANO_VENDA INT NOT NULL;

ALTER TABLE VENDAS_ANUAIS
ALTER COLUMN ID_MES_VENDA INT NOT NULL;

ALTER TABLE VENDAS_ANUAIS
ADD CONSTRAINT PK_COMPOSTA
PRIMARY KEY (
			ID_VENDAS, 
			ID_VEICULO,
			ID_ANO_VENDA,
			ID_MES_VENDA
			);

ALTER TABLE FABRICANTE ADD CONSTRAINT DF_ND_CONTATOs DEFAULT 'N/D' FOR contato;

ALTER TABLE ANO ADD CONSTRAINT UQ_ANO UNIQUE (ano);

ALTER TABLE MES ADD CONSTRAINT UQ_MES UNIQUE (mes);
